[project]
name = "{{cookiecutter.repo_name}}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "google-adk>=1.7.0",
    "google-cloud-aiplatform>=1.104.0",
    "google-genai>=1.26.0"
] 